version: '3.8'

services:
  web:
    build: ./validator_app
    command: uvicorn validator_app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/app/
    ports:
      - 8000:8000
